congig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectPizza.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectPizza/urls.py
from django.urls import path

from projectPizza import views
app_name='myapp'
urlpatterns = [
    path('', views.home,name='home'),
    path('menu/', views.menu,name='menu'),
    path('about/', views.about,name='about'),
    path('services/', views.services,name='services'),
    path('contact/', views.contact,name='contact'),

    path('<slug:category_slug>/',views.pizza_list, name='pizza_list_by_category'),
    path('<int:id>/<slug:slug>/',views.pizza_detail,name='pizza_detail')

]

projectPizza/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    """ Model for Category"""
    name=models.CharField(max_length=255, null=False,blank=False,unique=True,error_messages={"unique":"Bu nom allaqachon mavjud!"})
    slug=models.SlugField(max_length=255, null=False,blank=True, unique=True,error_messages={"unique":"Bu slug allaqachon mavjud!"})
    
    def get_absolute_url(self):
        return reverse('myapp:pizza_list_by_category',args=[self.slug])
    class Meta:
        verbose_name="Category"
        verbose_name_plural="Category"

    def __str__(self) :
        for_admin=f"{self.name} {self.slug}"
        return for_admin
    

class Pizza(models.Model):
    """Model ofr Pizza"""
    category=models.ForeignKey(Category,on_delete=models.CASCADE)  # category o'chsa pizza ham o'chib ketadi
    # category=models.ForeignKey(Category,on_delete=models.SET_NULL, null=True)  # category o'chsa pizza o'chmaydi
    # category=models.ForeignKey(Category,on_delete=models.SET_DEFAULT) 
    title=models.CharField(max_length=255)
    description=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    slug=models.SlugField(max_length=255, null=False,blank=True, unique=True,error_messages={"unique":"Bu slug allaqachon mavjud!"})
    image=models.ImageField(upload_to="Pizza/")
    update=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('myapp:pizza_detail',args=[self.id,self.slug])


    class Meta:
        verbose_name="Pizza"
        verbose_name_plural="Pizza"

    def __str__(self):
        for_admin=f"{self.title} {self.price} {self.created_at}"
        return for_admin

class PizzaNumber(models.Model):
    branches=models.PositiveIntegerField(default=1)
    awards=models.PositiveIntegerField(default=1)
    customer=models.PositiveIntegerField(default=1)
    staff=models.PositiveIntegerField(default=1)


    class Meta:
        verbose_name="Pizza Number"
        verbose_name_plural="Pizza Number"

    def __str__(self):
        for_admin=f"{self.branches} {self.awards} {self.customer}"
        return for_admin
    
class Chef(models.Model):
    name=models.CharField(max_length=100)    
    surname=models.CharField(max_length=100)  
    specialist=models.CharField(max_length=100)  
    description=models.TextField() 
    image=models.ImageField(upload_to='chef/')
    update=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Chef"
        verbose_name_plural="Chef"

    def __str__(self):
        for_admin=f"{self.name} {self.surname} {self.specialist}"
        return for_admin
    
    def full_name(self):
        return self.name + " " + self.surname

projectPizza/views.py
from django.shortcuts import render,get_object_or_404
from projectPizza.models import Pizza,PizzaNumber,Category,Chef
# Create your views here.

def home(request):
    pizza=Pizza.objects.all().order_by('-id')[:6]
    pizza_number=PizzaNumber.objects.all()
    categories=Category.objects.all()
    context={
        'pizza':pizza,
        'pizza_number':pizza_number,
        'categories':categories,
        }
    return render(request,'index.html',context)

def menu(request):
    pizza=Pizza.objects.all().order_by('-id')[:6]
    context={'pizza':pizza}
    return render(request,'menu.html',context)

def about(request):
    pizza=Pizza.objects.all().order_by('-id')[:6]
    chef=Chef.objects.all().order_by('-id')
    pizza_number=PizzaNumber.objects.all()
    context={
        'pizza_number':pizza_number,
        'pizza':pizza,
        'chef':chef

        }

    return render(request,'about.html',context)

def services(request):
    pizza=Pizza.objects.all()[:6]
    context={
        'pizza':pizza,
                }
    return render(request,'services.html',context)

def contact(request):
    return render(request,'contact.html')

def pizza_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()[:4]
    pizza=Pizza.objects.all()

    if category_slug:
        category=get_object_or_404(Category, slug=category_slug)
        pizza=pizza.filter(category=category)[:6]

    context={
            'pizza':pizza,
            'category':category,
            'categories':categories
        }
    return render(request,'index.html',context)


def pizza_detail(request,id,slug):
    pizza=get_object_or_404(Pizza,id=id,slug=slug)

    context={
        'pizza':pizza
    }
    return render(request,'pizza_detail.html',context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <section class="home-slider owl-carousel img" style="background-image: url({% static 'images/bg_1.jpg' %});">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">About</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>About</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>
    

    <section class="ftco-intro">
    	<div class="container-wrap">
    		<div class="wrap d-md-flex">
	    		<div class="info">
	    			<div class="row no-gutters">
	    				<div class="col-md-4 d-flex ftco-animate">
	    					<div class="icon"><span class="icon-phone"></span></div>
	    					<div class="text">
	    						<h3>000 (123) 456 7890</h3>
	    						<p>A small river named Duden flows</p>
	    					</div>
	    				</div>
	    				<div class="col-md-4 d-flex ftco-animate">
	    					<div class="icon"><span class="icon-my_location"></span></div>
	    					<div class="text">
	    						<h3>198 West 21th Street</h3>
	    						<p>Suite 721 New York NY 10016</p>
	    					</div>
	    				</div>
	    				<div class="col-md-4 d-flex ftco-animate">
	    					<div class="icon"><span class="icon-clock-o"></span></div>
	    					<div class="text">
	    						<h3>Open Monday-Friday</h3>
	    						<p>8:00am - 9:00pm</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="social d-md-flex pl-md-5 p-4 align-items-center">
	    			<ul class="social-icon">
              <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
            </ul>
	    		</div>
    		</div>
    	</div>
    </section>

    <section class="ftco-about d-md-flex">
    	<div class="one-half img" style="background-image: url({% static 'images/about.jpg' %});"></div>
    	<div class="one-half ftco-animate">
        <div class="heading-section ftco-animate ">
          <h2 class="mb-4">Welcome to <span class="flaticon-pizza">Pizza</span> A Restaurant</h2>
        </div>
        <div>
  				<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
  			</div>
    	</div>
    </section>

    <section class="ftco-section">
      <div class="container">
      	<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section ftco-animate text-center">
            <h2 class="mb-4">Our Chef</h2>
            <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
            <p class="mt-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="row">
			{% for ch in chef %}
        	<div class="col-lg-3 d-flex mb-sm-4 ftco-animate">
        		<div class="staff">
      				<div class="img mb-4" style="background-image: url({{ch.image.url}});"></div>
      				<div class="info text-center">
      					<h3><a href="teacher-single.html">{{ ch.full_name }}</a></h3>
      					<span class="position">{{ch.specialist}}</span>
      					<div class="text">
	        				<p>{{ ch.description }}</p>
	        			</div>
      				</div>
        		</div>
        	</div>
			{% endfor %}
        </div>
      </div>
    </section>


		<section class="ftco-counter ftco-bg-dark img" id="section-counter" style="background-image: url({% static 'images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
			<div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
        	<div class="col-md-10">
        		<div class="row">
					{% include 'pizza_number.html' %}
		        </div>
		    </div>
        </div>
      </div>
    </section>

	{% endblock content %}
    
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pizza - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
          <a class="navbar-brand" href="{% url 'myapp:home' %}"><span class="flaticon-pizza-1 mr-1"></span>Pizza<br><small>Delicous</small></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
          </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'myapp:home' %}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{% url 'myapp:menu' %}" class="nav-link">Menu</a></li>
          <li class="nav-item"><a href="{% url 'myapp:services' %}" class="nav-link">Services</a></li>
          <li class="nav-item"><a href="{% url 'myapp:about' %}" class="nav-link">About</a></li>
          <li class="nav-item"><a href="{% url 'myapp:contact' %}" class="nav-link">Contact</a></li>
        </ul>
      </div>
      </div>
  </nav>
{% block content %}
{% endblock content %}

<footer class="ftco-footer ftco-section img">
    <div class="overlay"></div>
  <div class="container">
    <div class="row mb-5">
      <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">About Us</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Recent Blog</h2>
          <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
            <div class="text">
              <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>
          <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
            <div class="text">
              <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
         <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Services</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">Cooked</a></li>
            <li><a href="#" class="py-2 d-block">Deliver</a></li>
            <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
            <li><a href="#" class="py-2 d-block">Mixed</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Have a Questions?</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
              </ul>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>



<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCDCNEk7drSVQK5BVcdpnddwFkcjSkzgic&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <section class="home-slider owl-carousel img" style="background-image: url({% static 'images/bg_1.jpg' %});">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Contact Us</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section contact-section">
      <div class="container mt-5">
        <div class="row block-9">
					<div class="col-md-4 contact-info ftco-animate">
						<div class="row">
							<div class="col-md-12 mb-4">
	              <h2 class="h4">Contact Information</h2>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
	            </div>
	            <div class="col-md-12 mb-3">
	              <p><span>Website:</span> <a href="#">yoursite.com</a></p>
	            </div>
						</div>
					</div>
					<div class="col-md-1"></div>
          <div class="col-md-6 ftco-animate">
            <form action="#" class="contact-form">
            	<div class="row">
            		<div class="col-md-6">
	                <div class="form-group">
	                  <input type="text" class="form-control" placeholder="Your Name">
	                </div>
                </div>
                <div class="col-md-6">
	                <div class="form-group">
	                  <input type="text" class="form-control" placeholder="Your Email">
	                </div>
	                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <div id="map"></div>

    {% endblock content %}
    
  </body>
</html>

templates/hot_pizza_meals.html
   <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <h2 class="mb-4">Oxirgi chiqqan pitsalar</h2>
        <p>Eng oxirgi turdagi mazzali pitsalar. Amerika mashxur pitsalaridan namunalar olindi</p>
      </div>
    </div>
    </div>
    <div class="container-wrap">
        
        <div class="row no-gutters d-flex">
            {% for pizz in pizza %}
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img" style="background-image: url({{ pizz.image.url }});"></a>
                    <div class="text p-4">
                        <h3>{{ pizz.title }}</h3>
                        <p>{{ pizz.description|slice:20}} </p>
                        <p class="price"><span>{{ pizz.price }} so'm</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Buyurtma</a></p>
                    </div>
                </div>
            </div>	
            {% endfor %}

        </div>
    </div>

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <section class="home-slider owl-carousel img" style="background-image: url({% static 'images/bg_1.jpg' %});">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Our Menu</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Menu</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>
    
	<section class="ftco-section">
		{% include 'hot_pizza_meals.html' %}

		{% include 'our_menu_pricing.html' %}

    </section>

	{% endblock content %}
    
  </body>
</html>

templates/our_menu_pricing.html
<div class="container">
    <div class="row justify-content-center mb-5 pb-3 mt-5 pt-5">
  <div class="col-md-7 heading-section text-center ftco-animate">
    <h2 class="mb-4">Our Menu Pricing</h2>
    <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
    <p class="mt-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
  </div>
</div>
<div class="row">
    
    {% for piz in pizza %}
    <div class="col-md-6">
        <div class="pricing-entry d-flex ftco-animate">
            <div class="img" style="background-image: url({{piz.image.url}});"></div>
            <div class="desc pl-3">
                <div class="d-flex text align-items-center">
                    <h3><span>{{piz.title}}</span></h3>
                    <span class="narxi">{{piz.price}} so'm</span>
                </div>
                <div class="d-block">
                    <p>{{piz.description|slice:40}}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
</div>

templates/pizza_number.html
{% for pizz in pizza_number %}
<div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
    <div class="block-18 text-center">
      <div class="text">
          <div class="icon"><span class="flaticon-pizza-1"></span></div>
          <strong class="number" data-number="{{pizz.branches}}">{{pizz.branches}}</strong>
          <span>Pizza Branches</span>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
    <div class="block-18 text-center">
      <div class="text">
          <div class="icon"><span class="flaticon-medal"></span></div>
          <strong class="number" data-number="{{pizz.awards}}">{{pizz.awards}}</strong>
          <span>Number of Awards</span>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
    <div class="block-18 text-center">
      <div class="text">
          <div class="icon"><span class="flaticon-laugh"></span></div>
          <strong class="number" data-number="{{pizz.customer}}">{{pizz.customer}}</strong>
          <span>Happy Customer</span>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
    <div class="block-18 text-center">
      <div class="text">
          <div class="icon"><span class="flaticon-chef"></span></div>
          <strong class="number" data-number="{{pizz.staff}}">{{pizz.staff}}</strong>
          <span>Staff</span>
      </div>
    </div>
  </div>
</div>
{% endfor %}

templates/services.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <section class="home-slider owl-carousel img" style="background-image: url({% static 'images/bg_1.jpg' %});">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Services</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Services</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>
    

    <section class="ftco-section ftco-services">
    	<div class="overlay"></div>
    	<div class="container">
    		<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section ftco-animate text-center">
            <h2 class="mb-4">Our Services</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
    		<div class="row">
          <div class="col-md-4 ftco-animate">
            <div class="media d-block text-center block-6 services">
              <div class="icon d-flex justify-content-center align-items-center mb-5">
              	<span class="flaticon-diet"></span>
              </div>
              <div class="media-body">
                <h3 class="heading">Healthy Foods</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>      
          </div>
          <div class="col-md-4 ftco-animate">
            <div class="media d-block text-center block-6 services">
              <div class="icon d-flex justify-content-center align-items-center mb-5">
              	<span class="flaticon-bicycle"></span>
              </div>
              <div class="media-body">
                <h3 class="heading">Fastest Delivery</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>      
          </div>
          <div class="col-md-4 ftco-animate">
            <div class="media d-block text-center block-6 services">
              <div class="icon d-flex justify-content-center align-items-center mb-5"><span class="flaticon-pizza-1"></span></div>
              <div class="media-body">
                <h3 class="heading">Original Recipes</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>    
          </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section">
    	{% include 'hot_pizza_meals.html' %}
    </section>

    {% endblock content %}
    
  </body>
</html>